-- Check columns in Companies and Products tables
SELECT 
    TABLE_NAME,
    COLUMN_NAME,
    DATA_TYPE,
    CHARACTER_MAXIMUM_LENGTH,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME IN ('Companies', 'Products')
ORDER BY TABLE_NAME, ORDINAL_POSITION;