import time
print("=" * 60)
print("SENDGRID MAGIC LINK TEST")
print("=" * 60)
print("\nYour SendGrid API key is configured in Azure Key Vault.")
print("The application is now running with Production email mode.")
print("\nTO TEST THE MAGIC LINK:")
print("1. Open your browser")
print("2. Go to: http://localhost:5193/Account/MagicLink")
print("3. Enter email: udi@fdx.trading")
print("4. Click 'Send Login Link'")
print("\nThe email should be sent via SendGrid to udi@fdx.trading")
print("\nIMPORTANT: Check your email inbox (and spam folder)")
print("The magic link email should arrive within 1-2 minutes.")
print("\n" + "=" * 60)