"""Add company order notification and payment tables

Revision ID: 97e2bd71866d
Revises: 1b4b3ade6855
Create Date: 2025-07-25 18:17:42.928517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '97e2bd71866d'
down_revision: Union[str, Sequence[str], None] = '1b4b3ade6855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('company_type', sa.Enum('BUYER', 'SUPPLIER', 'BOTH', name='companytype'), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_line2', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('company_size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', 'ENTERPRISE', name='companysize'), nullable=True),
    sa.Column('year_established', sa.Integer(), nullable=True),
    sa.Column('annual_revenue', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('verification_documents', sa.JSON(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.String(length=100), nullable=True),
    sa.Column('credit_limit', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('certifications', sa.JSON(), nullable=True),
    sa.Column('preferred_payment_methods', sa.JSON(), nullable=True),
    sa.Column('delivery_preferences', sa.JSON(), nullable=True),
    sa.Column('communication_preferences', sa.JSON(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('integration_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=True),
    sa.Column('can_place_orders', sa.Boolean(), nullable=True),
    sa.Column('can_approve_quotes', sa.Boolean(), nullable=True),
    sa.Column('preferred_language', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('communication_preferences', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('last_contacted', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_email'), 'contacts', ['email'], unique=False)
    op.create_index(op.f('ix_contacts_id'), 'contacts', ['id'], unique=False)
    op.create_table('communication_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('EMAIL', 'PHONE', 'SMS', 'MEETING', 'VIDEO_CALL', 'CHAT', 'SYSTEM', 'OTHER', name='communicationtype'), nullable=False),
    sa.Column('direction', sa.Enum('INBOUND', 'OUTBOUND', 'INTERNAL', name='communicationdirection'), nullable=False),
    sa.Column('from_user_id', sa.Integer(), nullable=True),
    sa.Column('to_user_id', sa.Integer(), nullable=True),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('subject', sa.String(length=500), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('email_message_id', sa.String(length=255), nullable=True),
    sa.Column('email_thread_id', sa.String(length=255), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('recording_url', sa.String(length=500), nullable=True),
    sa.Column('participants', sa.JSON(), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('outcome', sa.String(length=200), nullable=True),
    sa.Column('follow_up_required', sa.String(length=200), nullable=True),
    sa.Column('follow_up_date', sa.DateTime(), nullable=True),
    sa.Column('sentiment', sa.String(length=50), nullable=True),
    sa.Column('key_points', sa.JSON(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('communication_date', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_communication_logs_communication_date'), 'communication_logs', ['communication_date'], unique=False)
    op.create_index(op.f('ix_communication_logs_id'), 'communication_logs', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.Enum('NEW_RFQ', 'RFQ_RESPONSE', 'RFQ_EXPIRED', 'NEW_QUOTE', 'QUOTE_ACCEPTED', 'QUOTE_REJECTED', 'QUOTE_EXPIRED', 'ORDER_PLACED', 'ORDER_CONFIRMED', 'ORDER_SHIPPED', 'ORDER_DELIVERED', 'ORDER_CANCELLED', 'PAYMENT_RECEIVED', 'PAYMENT_OVERDUE', 'INVOICE_GENERATED', 'SYSTEM_ALERT', 'PRICE_ALERT', 'INVENTORY_ALERT', 'NEW_MESSAGE', 'DOCUMENT_SHARED', 'ACCOUNT_VERIFIED', 'PASSWORD_RESET', 'PROFILE_UPDATE', name='notificationtype'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('action_text', sa.String(length=100), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('channels', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('email_opened', sa.Boolean(), nullable=True),
    sa.Column('email_opened_at', sa.DateTime(), nullable=True),
    sa.Column('sms_sent', sa.Boolean(), nullable=True),
    sa.Column('sms_sent_at', sa.DateTime(), nullable=True),
    sa.Column('push_sent', sa.Boolean(), nullable=True),
    sa.Column('push_sent_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_company_id'), 'notifications', ['company_id'], unique=False)
    op.create_index(op.f('ix_notifications_created_at'), 'notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_type'), 'notifications', ['type'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_number', sa.String(length=50), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=True),
    sa.Column('buyer_company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_company_id', sa.Integer(), nullable=False),
    sa.Column('buyer_contact_id', sa.Integer(), nullable=True),
    sa.Column('supplier_contact_id', sa.Integer(), nullable=True),
    sa.Column('rfq_id', sa.Integer(), nullable=True),
    sa.Column('quote_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'COMPLETED', 'CANCELLED', 'REFUNDED', name='orderstatus'), nullable=False),
    sa.Column('payment_status', sa.Enum('PENDING', 'PARTIAL', 'PAID', 'OVERDUE', 'REFUNDED', name='paymentstatus'), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=True),
    sa.Column('shipping_amount', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('payment_due_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('requested_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('delivery_instructions', sa.Text(), nullable=True),
    sa.Column('shipping_method', sa.String(length=100), nullable=True),
    sa.Column('tracking_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('special_requirements', sa.Text(), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('confirmed_date', sa.DateTime(), nullable=True),
    sa.Column('shipped_date', sa.DateTime(), nullable=True),
    sa.Column('delivered_date', sa.DateTime(), nullable=True),
    sa.Column('completed_date', sa.DateTime(), nullable=True),
    sa.Column('cancelled_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['buyer_contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.ForeignKeyConstraint(['rfq_id'], ['rfqs.id'], ),
    sa.ForeignKeyConstraint(['supplier_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['supplier_contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.create_table('invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('buyer_company_id', sa.Integer(), nullable=False),
    sa.Column('supplier_company_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'VIEWED', 'PARTIAL', 'PAID', 'OVERDUE', 'CANCELLED', 'REFUNDED', name='invoicestatus'), nullable=False),
    sa.Column('invoice_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=True),
    sa.Column('tax_rate', sa.Integer(), nullable=True),
    sa.Column('shipping_amount', sa.Integer(), nullable=True),
    sa.Column('discount_amount', sa.Integer(), nullable=True),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('amount_paid', sa.Integer(), nullable=True),
    sa.Column('amount_due', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_terms', sa.String(length=200), nullable=True),
    sa.Column('payment_instructions', sa.Text(), nullable=True),
    sa.Column('bill_to_address', sa.Text(), nullable=True),
    sa.Column('ship_to_address', sa.Text(), nullable=True),
    sa.Column('buyer_tax_id', sa.String(length=50), nullable=True),
    sa.Column('supplier_tax_id', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('sent_date', sa.DateTime(), nullable=True),
    sa.Column('viewed_date', sa.DateTime(), nullable=True),
    sa.Column('paid_date', sa.DateTime(), nullable=True),
    sa.Column('sent_to_emails', sa.JSON(), nullable=True),
    sa.Column('reminder_count', sa.Integer(), nullable=True),
    sa.Column('last_reminder_date', sa.DateTime(), nullable=True),
    sa.Column('pdf_url', sa.String(length=500), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['supplier_company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoices_id'), 'invoices', ['id'], unique=False)
    op.create_index(op.f('ix_invoices_invoice_number'), 'invoices', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_invoices_status'), 'invoices', ['status'], unique=False)
    op.create_table('order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('product_sku', sa.String(length=100), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('quote_item_id', sa.Integer(), nullable=True),
    sa.Column('specifications', sa.JSON(), nullable=True),
    sa.Column('requested_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('confirmed_delivery_date', sa.DateTime(), nullable=True),
    sa.Column('quantity_shipped', sa.Float(), nullable=True),
    sa.Column('quantity_received', sa.Float(), nullable=True),
    sa.Column('quantity_invoiced', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('supplier_notes', sa.Text(), nullable=True),
    sa.Column('quality_requirements', sa.Text(), nullable=True),
    sa.Column('certifications_required', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.create_table('order_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=True),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('changed_by_name', sa.String(length=200), nullable=True),
    sa.Column('changed_by_role', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_status_history_created_at'), 'order_status_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_order_status_history_id'), 'order_status_history', ['id'], unique=False)
    op.create_index(op.f('ix_order_status_history_order_id'), 'order_status_history', ['order_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payment_number', sa.String(length=50), nullable=False),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('invoice_id', sa.Integer(), nullable=False),
    sa.Column('payer_company_id', sa.Integer(), nullable=False),
    sa.Column('payee_company_id', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('WIRE_TRANSFER', 'ACH', 'CHECK', 'CREDIT_CARD', 'PAYPAL', 'CASH', 'CREDIT_MEMO', 'OTHER', name='paymentmethod'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatus'), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('processing_fee', sa.Integer(), nullable=True),
    sa.Column('net_amount', sa.Integer(), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('cleared_date', sa.DateTime(), nullable=True),
    sa.Column('account_last_four', sa.String(length=4), nullable=True),
    sa.Column('routing_number_last_four', sa.String(length=4), nullable=True),
    sa.Column('processor', sa.String(length=50), nullable=True),
    sa.Column('processor_transaction_id', sa.String(length=255), nullable=True),
    sa.Column('processor_response', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.Column('is_reconciled', sa.Boolean(), nullable=True),
    sa.Column('reconciled_date', sa.DateTime(), nullable=True),
    sa.Column('reconciled_by_user_id', sa.Integer(), nullable=True),
    sa.Column('is_refund', sa.Boolean(), nullable=True),
    sa.Column('original_payment_id', sa.Integer(), nullable=True),
    sa.Column('refund_reason', sa.String(length=200), nullable=True),
    sa.Column('additional_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['original_payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['payee_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['payer_company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['reconciled_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_number'), 'payments', ['payment_number'], unique=True)
    op.add_column('activity_logs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activity_logs', 'companies', ['company_id'], ['id'])
    op.add_column('products', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'companies', ['company_id'], ['id'])
    op.add_column('rfqs', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('rfqs', sa.Column('assigned_contact_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rfqs', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'rfqs', 'contacts', ['assigned_contact_id'], ['id'])
    op.add_column('suppliers', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'suppliers', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'suppliers', type_='foreignkey')
    op.drop_column('suppliers', 'company_id')
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_constraint(None, 'rfqs', type_='foreignkey')
    op.drop_column('rfqs', 'assigned_contact_id')
    op.drop_column('rfqs', 'company_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'company_id')
    op.drop_constraint(None, 'activity_logs', type_='foreignkey')
    op.drop_column('activity_logs', 'company_id')
    op.drop_index(op.f('ix_payments_payment_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_status_history_order_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_id'), table_name='order_status_history')
    op.drop_index(op.f('ix_order_status_history_created_at'), table_name='order_status_history')
    op.drop_table('order_status_history')
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.drop_table('order_items')
    op.drop_index(op.f('ix_invoices_status'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_invoice_number'), table_name='invoices')
    op.drop_index(op.f('ix_invoices_id'), table_name='invoices')
    op.drop_table('invoices')
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_created_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_company_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_communication_logs_id'), table_name='communication_logs')
    op.drop_index(op.f('ix_communication_logs_communication_date'), table_name='communication_logs')
    op.drop_table('communication_logs')
    op.drop_index(op.f('ix_contacts_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_email'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.drop_table('companies')
    # ### end Alembic commands ###
