using System.Text;
using FDX.Trading.Models;
using FDX.Trading.Services;

namespace FDX.Trading.Services;

public class ImportResult
{
    public string FileName { get; set; } = "";
    public string UserType { get; set; } = "";
    public int TotalProcessed { get; set; }
    public int SuccessfulImports { get; set; }
    public int Skipped { get; set; }
    public List<string> Errors { get; set; } = new();
    public List<string> SkippedReasons { get; set; } = new();
    public List<User> ImportedUsers { get; set; } = new();
}

public class ImportedUserInfo
{
    public string Username { get; set; } = "";
    public string Password { get; set; } = "";
    public string CompanyName { get; set; } = "";
    public string Email { get; set; } = "";
    public string Status { get; set; } = "";
    public string Notes { get; set; } = "";
}

public class EnhancedImportService
{
    private const string DEFAULT_PASSWORD = "FDX2025!";

    public static async Task<ImportResult> ImportContractorsFromFile(string filePath, bool testMode = false, int testLimit = 5)
    {
        var result = new ImportResult();
        var existingUsernames = new HashSet<string>();

        if (!File.Exists(filePath))
        {
            result.Errors.Add($"File not found: {filePath}");
            return result;
        }

        var lines = await File.ReadAllLinesAsync(filePath);
        
        // Skip header
        for (int i = 1; i < lines.Length; i++)
        {
            if (testMode && result.SuccessfulImports >= testLimit)
                break;
                
            result.TotalProcessed++;
            
            try
            {
                var values = ParseCsvLine(lines[i]);
                
                if (values.Length < 12)
                {
                    result.SkippedReasons.Add($"Line {i + 1}: Insufficient columns");
                    result.Skipped++;
                    continue;
                }
                
                // Parse fields based on CSV structure
                var companyName = values[2]?.Trim() ?? ""; // Company name
                var category = values[3]?.Trim() ?? ""; // Category
                var website = values[4]?.Trim() ?? ""; // Website
                var email = values[5]?.Trim() ?? ""; // Email
                var country = values[6]?.Trim() ?? ""; // Country
                var phoneNumber = values[9]?.Trim() ?? ""; // Phone
                var address = values[11]?.Trim() ?? ""; // Address
                
                // Skip if no company name
                if (string.IsNullOrWhiteSpace(companyName))
                {
                    result.SkippedReasons.Add($"Line {i + 1}: No company name");
                    result.Skipped++;
                    continue;
                }
                
                // Check for duplicates
                if (existingUsernames.Contains(companyName.ToLower()))
                {
                    result.SkippedReasons.Add($"Line {i + 1}: Duplicate company '{companyName}'");
                    result.Skipped++;
                    continue;
                }
                
                // Determine if user is active (has email AND phone)
                bool isActive = !string.IsNullOrWhiteSpace(email) && !string.IsNullOrWhiteSpace(phoneNumber);
                bool dataComplete = isActive;
                
                // Generate placeholder email if missing
                if (string.IsNullOrWhiteSpace(email))
                {
                    email = $"{GenerateUsername(companyName)}@pending.fdx";
                }
                
                // Process category
                var categoryType = CategoryService.DetectCategory(companyName, "", category, false);
                var businessType = ExtractBusinessType(category);
                string? displayName = null;
                
                var user = new User
                {
                    // Id will be auto-generated by database
                    Username = GenerateUsername(companyName),
                    Password = DEFAULT_PASSWORD,
                    Email = email,
                    CompanyName = companyName,
                    Type = UserType.Expert,
                    Country = country,
                    PhoneNumber = phoneNumber,
                    Website = website,
                    Address = address,
                    Category = !string.IsNullOrEmpty(businessType) ? businessType : category,
                    CategoryId = categoryType,
                    BusinessType = businessType ?? "",
                    FullDescription = category,
                    SubCategories = "",
                    CreatedAt = DateTime.Now,
                    LastLogin = null,
                    IsActive = isActive,
                    RequiresPasswordChange = true,
                    DataComplete = dataComplete,
                    Verification = VerificationStatus.Pending,
                    DisplayName = displayName,
                    ImportedAt = DateTime.Now,
                    ImportNotes = dataComplete ? "Imported with complete data" : "Missing: " + 
                        (string.IsNullOrWhiteSpace(phoneNumber) ? "phone " : "") +
                        (email.Contains("@pending.fdx") ? "email" : "")
                };
                
                result.ImportedUsers.Add(user);
                existingUsernames.Add(companyName.ToLower());
                result.SuccessfulImports++;
            }
            catch (Exception ex)
            {
                result.Errors.Add($"Line {i + 1}: {ex.Message}");
            }
        }
        
        return result;
    }

    public static async Task<ImportResult> ImportBuyersFromFile(string filePath, bool testMode = false, int testLimit = 5)
    {
        var result = new ImportResult();
        var existingUsernames = new HashSet<string>();

        if (!File.Exists(filePath))
        {
            result.Errors.Add($"File not found: {filePath}");
            return result;
        }

        var fileContent = await File.ReadAllTextAsync(filePath);
        var rows = ParseMultiLineCsv(fileContent);
        
        // Skip header
        for (int i = 1; i < rows.Count; i++)
        {
            if (testMode && result.SuccessfulImports >= testLimit)
                break;
                
            result.TotalProcessed++;
            
            try
            {
                var values = rows[i];
                
                if (values.Length < 14)
                {
                    result.SkippedReasons.Add($"Row {i + 1}: Insufficient columns (found {values.Length}, need 14)");
                    result.Skipped++;
                    continue;
                }
                
                // Parse fields based on CSV structure
                var companyName = values[4]?.Trim() ?? ""; // Company name
                var description = values[6]?.Trim() ?? ""; // Business description
                var website = values[7]?.Trim() ?? ""; // Website
                var email = values[8]?.Trim() ?? ""; // Email
                var phoneNumber = values[9]?.Trim() ?? ""; // Phone
                var address = values[11]?.Trim() ?? ""; // Address
                var country = values[13]?.Trim() ?? ""; // Country
                
                // Skip if no company name
                if (string.IsNullOrWhiteSpace(companyName))
                {
                    result.SkippedReasons.Add($"Row {i + 1}: No company name");
                    result.Skipped++;
                    continue;
                }
                
                // Check for duplicates
                if (existingUsernames.Contains(companyName.ToLower()))
                {
                    result.SkippedReasons.Add($"Row {i + 1}: Duplicate company '{companyName}'");
                    result.Skipped++;
                    continue;
                }
                
                // Determine if user is active (has email AND phone)
                bool isActive = !string.IsNullOrWhiteSpace(email) && !string.IsNullOrWhiteSpace(phoneNumber);
                bool dataComplete = isActive;
                
                // Generate placeholder email if missing
                if (string.IsNullOrWhiteSpace(email))
                {
                    email = $"{GenerateUsername(companyName)}@pending.fdx";
                }
                
                // Process category from description
                var categoryType = CategoryService.DetectCategory(companyName, description, "", true);
                var businessType = ExtractBusinessType(description);
                string? displayName = null;
                
                var user = new User
                {
                    // Id will be auto-generated by database
                    Username = GenerateUsername(companyName),
                    Password = DEFAULT_PASSWORD,
                    Email = email,
                    CompanyName = companyName,
                    Type = UserType.Buyer,
                    Country = country,
                    PhoneNumber = phoneNumber,
                    Website = website,
                    Address = address,
                    Category = !string.IsNullOrEmpty(businessType) ? businessType : ExtractBusinessType(description),
                    CategoryId = categoryType,
                    BusinessType = businessType ?? ExtractBusinessType(description),
                    FullDescription = description,
                    SubCategories = "",
                    CreatedAt = DateTime.Now,
                    LastLogin = null,
                    IsActive = isActive,
                    RequiresPasswordChange = true,
                    DataComplete = dataComplete,
                    Verification = VerificationStatus.Pending,
                    DisplayName = displayName,
                    ImportedAt = DateTime.Now,
                    ImportNotes = dataComplete ? "Imported with complete data" : "Missing: " + 
                        (string.IsNullOrWhiteSpace(phoneNumber) ? "phone " : "") +
                        (email.Contains("@pending.fdx") ? "email" : "")
                };
                
                result.ImportedUsers.Add(user);
                existingUsernames.Add(companyName.ToLower());
                result.SuccessfulImports++;
            }
            catch (Exception ex)
            {
                result.Errors.Add($"Row {i + 1}: {ex.Message}");
            }
        }
        
        return result;
    }
    
    private static string ExtractBusinessType(string description)
    {
        if (string.IsNullOrWhiteSpace(description))
            return "";
            
        // Look for "is a" pattern
        var isAIndex = description.IndexOf(" is a ", StringComparison.OrdinalIgnoreCase);
        if (isAIndex > 0)
        {
            var startIndex = isAIndex + 6;
            var endIndex = description.IndexOf('.', startIndex);
            if (endIndex == -1)
                endIndex = description.IndexOf(',', startIndex);
            if (endIndex == -1)
                endIndex = Math.Min(description.Length, startIndex + 100);
                
            var extracted = description.Substring(startIndex, endIndex - startIndex).Trim();
            
            // Limit length
            if (extracted.Length > 50)
            {
                var lastSpace = extracted.LastIndexOf(' ', 50);
                if (lastSpace > 0)
                    extracted = extracted.Substring(0, lastSpace) + "...";
                else
                    extracted = extracted.Substring(0, 50) + "...";
            }
            
            return extracted;
        }
        
        // Fallback: take first sentence or part
        var firstPeriod = description.IndexOf('.');
        var firstComma = description.IndexOf(',');
        var cutoff = firstPeriod > 0 && (firstComma == -1 || firstPeriod < firstComma) ? firstPeriod : firstComma;
        
        if (cutoff > 0 && cutoff < 100)
            return description.Substring(0, cutoff).Trim();
            
        // Last resort: truncate
        return description.Length > 50 ? description.Substring(0, 50) + "..." : description;
    }
    
    private static string GenerateUsername(string companyName)
    {
        if (string.IsNullOrWhiteSpace(companyName))
            return "user" + Guid.NewGuid().ToString("N").Substring(0, 8);
            
        // Check if Hebrew
        bool hasHebrew = companyName.Any(c => c >= 0x0590 && c <= 0x05FF);
        if (hasHebrew)
        {
            // Generate random username for Hebrew names
            return "user_" + Guid.NewGuid().ToString("N").Substring(0, 8);
        }
        
        // Clean and format username
        var username = companyName.ToLower()
            .Replace(" ", "_")
            .Replace("-", "_")
            .Replace(".", "")
            .Replace(",", "")
            .Replace("(", "")
            .Replace(")", "")
            .Replace("/", "_")
            .Replace("\\", "_")
            .Replace("&", "and")
            .Replace("'", "")
            .Replace("\"", "");
            
        // Remove multiple underscores
        while (username.Contains("__"))
            username = username.Replace("__", "_");
            
        // Trim underscores
        username = username.Trim('_');
        
        // Limit length
        if (username.Length > 30)
            username = username.Substring(0, 30);
            
        // Ensure it starts with a letter
        if (username.Length > 0 && !char.IsLetter(username[0]))
            username = "u_" + username;
            
        // If empty, generate random
        if (string.IsNullOrWhiteSpace(username))
            username = "user_" + Guid.NewGuid().ToString("N").Substring(0, 8);
            
        return username;
    }
    
    private static List<string[]> ParseMultiLineCsv(string content)
    {
        var rows = new List<string[]>();
        var currentRow = new List<string>();
        var currentField = new StringBuilder();
        var inQuotes = false;
        var previousChar = '\0';
        
        for (int i = 0; i < content.Length; i++)
        {
            var ch = content[i];
            
            if (ch == '"')
            {
                if (inQuotes && i + 1 < content.Length && content[i + 1] == '"')
                {
                    // Escaped quote
                    currentField.Append('"');
                    i++; // Skip next quote
                }
                else
                {
                    inQuotes = !inQuotes;
                }
            }
            else if (ch == ',' && !inQuotes)
            {
                // End of field
                currentRow.Add(currentField.ToString());
                currentField.Clear();
            }
            else if ((ch == '\n' || ch == '\r') && !inQuotes)
            {
                // End of row (but skip empty lines)
                if (ch == '\n' || (ch == '\r' && i + 1 < content.Length && content[i + 1] != '\n'))
                {
                    if (currentRow.Count > 0 || currentField.Length > 0)
                    {
                        currentRow.Add(currentField.ToString());
                        rows.Add(currentRow.ToArray());
                        currentRow.Clear();
                        currentField.Clear();
                    }
                }
            }
            else if (ch != '\r' || inQuotes)
            {
                currentField.Append(ch);
            }
            
            previousChar = ch;
        }
        
        // Add last row if any
        if (currentRow.Count > 0 || currentField.Length > 0)
        {
            currentRow.Add(currentField.ToString());
            rows.Add(currentRow.ToArray());
        }
        
        return rows;
    }
    
    private static string[] ParseCsvLine(string line)
    {
        var values = new List<string>();
        var currentValue = new StringBuilder();
        var inQuotes = false;

        for (int i = 0; i < line.Length; i++)
        {
            var ch = line[i];

            if (ch == '"')
            {
                if (inQuotes && i + 1 < line.Length && line[i + 1] == '"')
                {
                    currentValue.Append('"');
                    i++; // Skip next quote
                }
                else
                {
                    inQuotes = !inQuotes;
                }
            }
            else if (ch == ',' && !inQuotes)
            {
                values.Add(currentValue.ToString());
                currentValue.Clear();
            }
            else
            {
                currentValue.Append(ch);
            }
        }

        values.Add(currentValue.ToString());
        return values.ToArray();
    }

    public static string GenerateImportReport(List<ImportResult> results)
    {
        var sb = new StringBuilder();
        sb.AppendLine("Username,Password,CompanyName,Email,Type,Status");
        
        foreach (var result in results)
        {
            foreach (var user in result.ImportedUsers)
            {
                sb.AppendLine($"\"{user.Username}\",\"{user.Password}\",\"{user.CompanyName}\",\"{user.Email}\",\"{user.Type}\",\"{(user.IsActive ? "Active" : "Inactive")}\"");
            }
        }
        
        return sb.ToString();
    }
}